spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbnews
    username: root
    password: asdfghjkl
  redis:
    client-name: JEDIS
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    propbernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

      server:
        port: 8081

      secret:
        jwt: "orientcourseorientcourseorientcourseorientcourseorientcourseorientcourse"
      jackson:
        default-property-inclusion: NON_NULL
        serialization:
          write_dates_as_timestamps: false